package rcarmstrong20.vanilla_expansions.enums;

import net.minecraft.world.biome.Biome;
import net.minecraft.world.biome.Biomes;

public enum VeOverworldBiomeConfig
{
	OCEAN(Biomes.OCEAN),
	PLAINS(Biomes.PLAINS),
	DESERT(Biomes.DESERT),
	MOUNTAINS(Biomes.MOUNTAINS),
	FOREST(Biomes.FOREST),
	TAIGA(Biomes.TAIGA),
	SWAMP(Biomes.SWAMP),
	RIVER(Biomes.RIVER),
	FROZEN_OCEAN(Biomes.FROZEN_OCEAN),
	FROZEN_RIVER(Biomes.FROZEN_RIVER),
	SNOWY_TUNDRA(Biomes.SNOWY_TUNDRA),
	SNOWY_MOUNTAINS(Biomes.SNOWY_MOUNTAINS),
	MUSHROOM_FIELDS(Biomes.MUSHROOM_FIELDS),
	MUSHROOM_FIELD_SHORE(Biomes.MUSHROOM_FIELD_SHORE),
	BEACH(Biomes.BEACH),
	DESERT_HILLS(Biomes.DESERT_HILLS),
	WOODED_HILLS(Biomes.WOODED_HILLS),
	TAIGA_HILLS(Biomes.TAIGA_HILLS),
	MOUNTAIN_EDGE(Biomes.MOUNTAIN_EDGE),
	JUNGLE(Biomes.JUNGLE),
	JUNGLE_HILLS(Biomes.JUNGLE_HILLS),
	JUNGLE_EDGE(Biomes.JUNGLE_EDGE),
	DEEP_OCEAN(Biomes.DEEP_OCEAN),
	STONE_SHORE(Biomes.STONE_SHORE),
	SNOWY_BEACH(Biomes.SNOWY_BEACH),
	BIRCH_FOREST(Biomes.BIRCH_FOREST),
	BIRCH_FOREST_HILLS(Biomes.BIRCH_FOREST_HILLS),
	DARK_FOREST(Biomes.DARK_FOREST),
	SNOWY_TAIGA(Biomes.SNOWY_TAIGA),
	SNOWY_TAIGA_HILLS(Biomes.SNOWY_TAIGA_HILLS),
	GIANT_TREE_TAIGA(Biomes.GIANT_TREE_TAIGA),
	GIANT_TREE_TAIGA_HILLS(Biomes.GIANT_TREE_TAIGA_HILLS),
	WOODED_MOUNTAINS(Biomes.WOODED_MOUNTAINS),
	SAVANNA(Biomes.SAVANNA),
	SAVANNA_PLATEAU(Biomes.SAVANNA_PLATEAU),
	BADLANDS(Biomes.BADLANDS),
	WOODED_BADLANDS_PLATEAU(Biomes.WOODED_BADLANDS_PLATEAU),
	BADLANDS_PLATEAU(Biomes.BADLANDS_PLATEAU),
	WARM_OCEAN(Biomes.WARM_OCEAN),
	LUKEWARM_OCEAN(Biomes.LUKEWARM_OCEAN),
	COLD_OCEAN(Biomes.COLD_OCEAN),
	DEEP_WARM_OCEAN(Biomes.DEEP_WARM_OCEAN),
	DEEP_LUKEWARM_OCEAN(Biomes.DEEP_LUKEWARM_OCEAN),
	DEEP_COLD_OCEAN(Biomes.DEEP_COLD_OCEAN),
	DEEP_FROZEN_OCEAN(Biomes.DEEP_FROZEN_OCEAN),
	SUNFLOWER_PLAINS(Biomes.SUNFLOWER_PLAINS),
	DESERT_LAKES(Biomes.DESERT_LAKES),
	GRAVELLY_MOUNTAINS(Biomes.GRAVELLY_MOUNTAINS),
	FLOWER_FOREST(Biomes.FLOWER_FOREST),
	TAIGA_MOUNTAINS(Biomes.TAIGA_MOUNTAINS),
	SWAMP_HILLS(Biomes.SWAMP_HILLS),
	ICE_SPIKES(Biomes.ICE_SPIKES),
	MODIFIED_JUNGLE(Biomes.MODIFIED_JUNGLE),
	MODIFIED_JUNGLE_EDGE(Biomes.MODIFIED_JUNGLE_EDGE),
	TALL_BIRCH_FOREST(Biomes.TALL_BIRCH_FOREST),
	TALL_BIRCH_HILLS(Biomes.TALL_BIRCH_HILLS),
	DARK_FOREST_HILLS(Biomes.DARK_FOREST_HILLS),
	SNOWY_TAIGA_MOUNTAINS(Biomes.SNOWY_TAIGA_MOUNTAINS),
	GIANT_SPRUCE_TAIGA(Biomes.GIANT_SPRUCE_TAIGA),
	GIANT_SPRUCE_TAIGA_HILLS(Biomes.GIANT_SPRUCE_TAIGA_HILLS),
	MODIFIED_GRAVELLY_MOUNTAINS(Biomes.MODIFIED_GRAVELLY_MOUNTAINS),
	SHATTERED_SAVANNA(Biomes.SHATTERED_SAVANNA),
	SHATTERED_SAVANNA_PLATEAU(Biomes.SHATTERED_SAVANNA_PLATEAU),
	ERODED_BADLANDS(Biomes.ERODED_BADLANDS),
	MODIFIED_WOODED_BADLANDS_PLATEAU(Biomes.MODIFIED_WOODED_BADLANDS_PLATEAU),
	MODIFIED_BADLANDS_PLATEAU(Biomes.MODIFIED_BADLANDS_PLATEAU),
	BAMBOO_JUNGLE(Biomes.BAMBOO_JUNGLE),
	BAMBOO_JUNGLE_HILLS(Biomes.BAMBOO_JUNGLE_HILLS);
	
	private final Biome biome;
	
	private VeOverworldBiomeConfig(Biome biome)
	{
		this.biome = biome;
	}
	
	public Biome getBiome()
	{
		return this.biome;
	}
}
